apiVersion: v1
kind: Service
metadata:
  name: txwl-{{.Release.Name}} # 一定要以txwl开头，否则prometheus federation拉不上去
  labels:
    app: {{ .Values.huiju.name }}
    instance: {{ .Release.Name }}
spec:
  ports:
    - port: 8080
      targetPort: 22122
      name: metrics-port
  selector:
    app: {{ .Values.huiju.name }}
    instance: {{ .Release.Name }}